feat: fetaure email identities.
clouddrove/terraform-aws-ses pull request #24
Opened 2023-07-27 15:59 UTC by nileshgadgi

## what
* Feature E-Mail identities in AWS SES.
* Remove unnecessary variables.
* Add and updated the required changes in the workflows.

## why
* To enhance the module usability and accessibility for ease of use.

## references
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_email_identity

2023-07-27 16:57 UTC, nikitadugar requested changes

2023-07-27 16:57 UTC, nikitadugar commented on main.tf
> +  count = var.enable_email ? length(var.emails) : 0
missing var.enabled here in condition

2023-07-27 16:57 UTC, nikitadugar commented on main.tf
> +  count  = var.enable_domain ? 1 : 0
same var.enabled missing here

2023-07-27 17:15 UTC, nileshgadgi commented on main.tf
> +  count = var.enable_email ? length(var.emails) : 0
Fixed. 👍🏼

2023-07-27 17:16 UTC, nileshgadgi commented on main.tf
> +  count  = var.enable_domain ? 1 : 0
Fixed. 👍🏼

2023-07-28 14:51 UTC, nikitadugar approved these changes

2023-07-28 17:35 UTC, themaniskshah approved these changes
LGTM!

2023-07-28 17:37 UTC, merged